services:
  postgres:
    image: postgres:16
    container_name: noteflow-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ../NoteFlow_Auth-service
    container_name: noteflow-auth-service
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      APP_NAME: NoteFlow Auth Service
      APP_VERSION: 0.1.0
      DEBUG: "false"
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: change_this_to_a_long_random_secret_key_32_chars_min
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "${AUTH_SERVICE_PORT}:8001"

  notes-data-service:
    build:
      context: ../NoteFlow_Notes-Data-service
    container_name: noteflow-notes-data-service
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      NOTES_DATA_SERVICE_HOST: 0.0.0.0
      NOTES_DATA_SERVICE_PORT: ${NOTES_DATA_SERVICE_PORT}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${NOTES_DATA_SERVICE_PORT}:8003"

  adminer:
    image: adminer:4
    container_name: noteflow-adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  postgres_data:
