apiVersion: v1
kind: ConfigMap
metadata:
  name: noteflow-config
  namespace: noteflow
data:
  POSTGRES_DB: noteflow
  POSTGRES_USER: noteflow_user
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  AUTH_SERVICE_URL: http://auth-service:8001
  NOTES_DATA_SERVICE_URL: http://notes-data-service:8003
---
apiVersion: v1
kind: Secret
metadata:
  name: noteflow-secret
  namespace: noteflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: noteflow_pass
  JWT_SECRET_KEY: change_this_to_a_long_random_secret_key_32_chars_min
  GRAFANA_ADMIN_PASSWORD: admin

