name: Build NoteFlow Images

on:
  push:
    branches: ["main", "andrei"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build auth-service
        run: docker build -t noteflow/auth-service:latest ../NoteFlow_Auth-service

      - name: Build notes-service
        run: docker build -t noteflow/notes-service:latest ../NoteFlow_Notes-service

      - name: Build notes-data-service
        run: docker build -t noteflow/notes-data-service:latest ../NoteFlow_Notes-data-service

      - name: Validate compose
        run: docker compose -f docker-compose.dev.yml config